[package]
name = "libnewsboat-ffi"
version = "2.22.0"
authors = ["Alexander Batischev <eual.jp@gmail.com>"]
edition = "2018"

[dependencies]
libnewsboat = { path="../libnewsboat" }
libc = "0.2"
cxx = "0.5"

[build-dependencies]
cxx-build = "0.5"

[lib]
name = "newsboat"
crate-type = ["staticlib"]
