[package]
name = "libnewsboat-ffi"
version = "2.20.0"
authors = ["Alexander Batischev <eual.jp@gmail.com>"]
edition = "2018"

[dependencies]
libnewsboat = { path="../libnewsboat" }
libc = "0.2"

[lib]
name = "newsboat"
crate-type = ["staticlib"]
